### ISSUE TITLE
Make animate.css optional

### ISSUE THREAD

**Issue by upq** [dbramwell/react-animate-on-scroll#2]
Animate.css is nice, but in my use case and I think many other cases we have our own custom animations and all those animations in animate.css are not likely to be used.

besides I had problems with the minified 
```
 (function (exports, require, module, __filename, __dirname) { @charset "UTF-8";
                                                              ^
SyntaxError: Unexpected token ILLEGAL 
```
Thats why I forked and using a custom version of react-animate-on-scroll.

Thanks

**Comment by dbramwell** [comment]
The custom animations should just work right? As all animate on scroll does is give a class to an element at a certain point.

Do you think it would be better for me to remove animate.CSS from the build and let people include it if they wish?

**Comment by dbramwell** [comment]
Sorry, just read the title of the pull request. Will remove it from the finished build.

**Comment by dbramwell** [comment]
In version 1.2.0 animate.css is no longer included. Let me know how you get on and if we can close this issue.

**Comment by upq** [comment]
Yes any class works fine thats why I suggest making animate.css optional, Im closing the issue too, thanks 👍

**Comment by oyeanuj** [comment]
@dbramwell Could you also provide an example of how to use this library with custom animations?

I am looking to use https://github.com/FormidableLabs/react-animations instead of `animate.css` but not sure how to make it work with this library.

Thank you!

**Comment by dbramwell** [comment]
Hi @oyeanuj 

Can you give more of an example of what you're trying to achieve? All react-animate-on-scroll really does is add a class to an element when it's scrolled into view. That class relates to an animation defined in CSS somewhere. If you include animate.css, react-animate-on-scroll can add any of those classes to the element when it scrolls into view. Similarly, if you defined an animation in CSS along the lines of:
```
.fadeFromRedToBlue {
  clever-fade-implementation-of-some-sort
}
```
Then you could use react-animate-on-scroll to add the 'fadeFromRedToBlue' class to an element when it's scrolled into view.

React-animations seems to allow different ways to add animate.css animations to your application, rather than provide animations itself? I'm not sure what you're trying to achieve but hopefully the info above will help you

**Comment by oyeanuj** [comment]
@dbramwell I see. So, it wasn't clear to me from the README that only a classname was being added and via which prop? Is that the `animateIn` prop?

**Comment by dbramwell** [comment]
Yeah, whatever you set as the animateIn prop is set as a class when the element is scrolled into view. The animateOut prop does the same but when you scroll out of view
