### ISSUE TITLE
Animations not firing if body and html scroll bar hidden ?

### ISSUE THREAD

**Issue by ldevalbray** [dbramwell/react-animate-on-scroll#30]
Would it be possible that the animations are not firing because it listens to the html/body scroll bar only ? If so, would it be possible to add our own css tag as a parameter to the component ? (So that it listens to its scroll bar and no more to the html/body one)

**Comment by dbramwell** [comment]
Hey, yeah it looks at the window object. It's probably possible to have a prop such as "parentSelector" or some such that points to the parent element, then in the constructor we can check for that prop, use "window" if it isn't set, otherwise use the element found by the parent selector.

I probably won't have chance to work on this for a while, but if you have time a pull request would be greatly appreciated!

**Comment by dbramwell** [comment]
I've had a crack at it. The new [scrollableParentSelector](https://dbramwell.github.io/react-animate-on-scroll/#scrollableParentSelector) prop should allow you to specify the element that is being scrolled. I've tested in chrome and firefox, but not IE.

Just pass a css selector that points to the parent element that has the scroll bars. Let me know if you see any issues.
