### ISSUE TITLE
Change dynamic animation

### ISSUE THREAD

**Issue by maxval94** [dbramwell/react-animate-on-scroll#32]
Hi, i want to change dynamic animationName, animationDelay, animationDuration.
For now it is impossible, how i can do that?
Example https://codesandbox.io/s/7w3r262701

**Comment by dbramwell** [comment]
Hey, sorry for the delay.

I'm not too sure what your issue is. Is it just that you want to dynamically set the animateIn prop with a select? If so, that's completely possible, your example isn't quite there though. 

1. Your select has options of fadeIn and fadeOut, but fadeOut is an exit animation, so doesn't look great when used with animateIn.

2. The first option on your select is the one that is selected by default when the page loads, and is "fadeout". But you also set state.animateIn to fadeIn, which is the other select option.

To see a better example of it working, swap your two select options around, and then replace fadeOut with zoomIn.

**Comment by maxval94** [comment]
Thanks!

**Comment by dbramwell** [comment]
No worries
