### ISSUE TITLE
Don't call animation until user scrolls?

### ISSUE THREAD

**Issue by mikeriley131** [dbramwell/react-animate-on-scroll#39]
Great package.

Is there a way to not fire an animation until the user has scrolled? I have a hero that animates on page load (not using the `ScrollAnimation` component) and then sections below that that are typically "below the fold" that use `ScrollAnimation`. However on some larger and hi-res screens those secondary sections are in the viewport on page load and thus kick off the CSS animation tied to that `ScrollAnimation` component. I'm wondering if there's a way to ensure those don't kick off until the user has actually scrolled.

Thanks.

**Comment by dbramwell** [comment]
Thanks.

Fair request. The current functionality is what I wanted, but you're right, no reason not to have both options. I've just released a new version to npm with the `animatePreScroll` prop. By default this is set to true. Set it to false to get the result I think you're looking for.

I've added a (kind of crappy, but I couldn't think of a better one) example to the [demo](https://dbramwell.github.io/react-animate-on-scroll/#animatePreScroll). Obviously you can just use it in your page as normal, rather than in a scrollable div.

Does this do what you want?

**Comment by firstpersoncode** [comment]
Does this only work if **scrollableParentSelector** defaults to the document?
I tried setting **scrollableParentSelector** to the parent div that contains the animated scroll elements, but it didn't work as expected. I had to scroll until I passed the element first, and nothing happen, then scroll back above the element, and finally scroll past the element again until it worked.
