### ISSUE TITLE
Warning: called setState on unmounted component

### ISSUE THREAD

**Issue by MSliger** [dbramwell/react-animate-on-scroll#5]
I keep getting this error in the console anytime I change Routes in my app: 
// proxyConsole.js:56 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ScrollAnimation component. //

**Comment by dbramwell** [comment]
Hi. Can you share your project? Or give me a simple way of reproducing the error?

**Comment by hawkins** [comment]
Similarly, I see this when I HMR a component that has a `react-animate-on-scroll` on it. In that case, it's obviously on an unmounted component.

For instance, take a Next.js site:

1. Load the page
    - Functions as expected
2. Make a change to the code - HMR updates this live
3. Scroll
    - Observe the warning placed in console

**Comment by dbramwell** [comment]
You mean [this next.js](https://github.com/zeit/next.js/)? I tried to set up a simple app using it and I get bigger issues than the above:
`ReferenceError: window is not defined
at new ScrollAnimation (C:\Dev\nextTest\node_modules\react-animate-on-scroll\dist\scrollAnimation.min.js:57:9)`

I'm assuming because NextJS does serverside rendering so it doesn't have access to the window object?

Regarding the original issue, could it simply be that we're removing the wrong event listener?

[window.addEventListener("scroll", throttle(this.handleScroll.bind(this), 200));](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js#L27)

vs

[window.removeEventListener("scroll", this.handleScroll.bind(this));](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js#L40)

If one of you could try changing L40 to match L27 in a project that's giving you the warning I'd be most appreciative!

**Comment by hawkins** [comment]
Yes, that next.js. For clarity, I'm using it like this to avoid SSR issues:

```javascript
import dynamic from "next/dynamic";

const ScrollAnimation = dynamic(import("react-animate-on-scroll"), {
  loading: ({ children }) =>
    <div>
      {children}
    </div>,
  ssr: false
});

export default props => <ScrollAnimation offset={0} animateOnce {...props} />;
```

I'll give that change a shot and report back.

**Comment by dbramwell** [comment]
I got around the window issue with this:
https://github.com/kadirahq/react-no-ssr

Still can't reproduce the error though :(

**Comment by hawkins** [comment]
Cool, that's effectively the same logic. Even written by the same author!

On topic, I can't reproduce it anymore, either. Neither with original source code, or modified, or with assigning the `throttle`'d function to a `this.listener` member and removing the listener by name. I'm not exactly sure how we ran into this on my team now, then... I'll be sure to post back here when it shows up again!

**Comment by dbramwell** [comment]
I've reproduced it in the demo in this [branch](https://github.com/dbramwell/react-animate-on-scroll/tree/reproduce_setstate_on_unmounted_component_warning)

On clicking the button it removes the ScrollAnimation further down the page, when scrolling to it I then see the warning. The fix was to remove the event listener properly, not sure why I didn't spot that issue before.

1.3.2 is released and contains the fix. Thanks guys

**Comment by hawkins** [comment]
Nice job! Happy to see I was onto something with naming the function as a member, too! 👍
